version: '3'
services:
  app:
    container_name: docker-node-mongo
    env_file:
      - ./envs/local.env
    restart: always
    build: .
    volumes:
      - .:/code
    ports:
      - '80:3005'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'